sudo: false
language: python
python:
- '2.7'
- '3.6'
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pycodestyle
  - npm install -g jshint
  - cp travis-ci/manage.py manage.py
script:
  - pycodestyle notify/ --exclude=migrations
  - jshint notify/static/js/ --verbose
  - coverage run --source=notify/ --omit=notify/migrations/* manage.py test notify
after_success:
  - coveralls
notifications:
