version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      AUTH: SAML_MOCK
    restart: always
    container_name: app-notify
    build:
      context: .
      target: app-container
    volumes:
      - ./notify:/app/notify
    ports:
      - "8000:8000"
