version: '2'

services:
  app:
    environment:
      - ENV=localdev
      - PORT=8000
      - AUTH=SAML_MOCK
    restart: always
    container_name: app-notifyuw
    build:
      context: .
    volumes:
      - ./notify:/app/notify
    ports:
      - "8000:8000"
  devtools:
