ingress:
  enabled: true
  tls:
    notify:
      secretName: notify.uw.edu-ingress-cert
      hosts:
        - prod.notify.uw.edu
  hosts:
    notify:
      host: prod.notify.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
readiness:
  enabled: true
externalService:
  enabled: true
  name: notify-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.34
  servicePort: 5432
database:
  engine: postgres
  name: notify-prod
  hostname: notify-db-service
  secretName: notify.uw.edu-db
repo: notify
instance: prod
image:
  repository: registry.hub.docker.com/acait/notify
  tag: IMAGE_TAG
replicaCount: 2
minReplicas: 2
maxReplicas: 4
targetAverageUtilization: 90
resources:
  limits:
    cpu: 600m
  requests:
    cpu: 200m
memcached:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: true
  jobs:
    - name: unsubscribe-registered
      schedule: '*/5 15-23 * * 1-5'
      command: [/scripts/management_command.sh registration_consumer]
certs:
  mounted: true
  certPath: /certs/notify.uw.edu-uwca.cert
  keyPath: /certs/notify.uw.edu-uwca.key
  secretName: notify.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: prod
  - name: KWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: SWS_ENV
    value: PROD
  - name: NWS_ENV
    value: PROD
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://prod.notify.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: prod.notify.uw.edu
  - name: SAML_USER_ATTRIBUTE
    value: eppn
  - name: SP_CERT
    value: 'MIIG+jCCBeKgAwIBAgIQfAFBcU6E/5BVGeZy135nWTANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjEfMB0GA1UEAxMWSW5Db21tb24gUlNBIFNlcnZlciBDQTAeFw0yMDA1MDUwMDAwMDBaFw0yMjA1MDUyMzU5NTlaMIGvMQswCQYDVQQGEwJVUzEOMAwGA1UEERMFOTgxOTUxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1NlYXR0bGUxGTAXBgNVBAkTEDQ1NDUgMTV0aCBBdmUgTkUxITAfBgNVBAoTGFVuaXZlcnNpdHkgb2YgV2FzaGluZ3RvbjEOMAwGA1UECxMFVVctSVQxGzAZBgNVBAMTEnByb2Qubm90aWZ5LnV3LmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALcpGPsmaFmA8lXZjLtZnJr4i4fDRyLrSGYZN8/UemY4zQZre5oF/DOxR9DYU9RQDrd9qMQJtAEnc5GClOIpGO4vl3bim/YwtJ4izJJpS4gubbjEeDREQKeVo/j3ehTJ59LWIq9+Y/c8Jg8EqYF1B0tupEZNat7IaeUW0XkdhEb06OBO02+nhUgp2txSbwrkr1zKdVWgwxxAC7uMcgzQ+B5EWOKzXGa+czWIvfVXqujZoxsKCLeWWz6MeBkOCIh6B5rxxSc9zlhEjHKZWGShq1XswIFk77sTSnzK1ltZXt3iiAegHec/7j9hvSA0o+Kbzx4EwGBMktMzbUauCGvfmQkCAwEAAaOCA0gwggNEMB8GA1UdIwQYMBaAFB4Fo3ePbJbiW4dLprSGrHEADOc4MB0GA1UdDgQWBBSclZI0DDApnYZIv72r8Or6Un5csTAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwZwYDVR0gBGAwXjBSBgwrBgEEAa4jAQQDAQEwQjBABggrBgEFBQcCARY0aHR0cHM6Ly93d3cuaW5jb21tb24ub3JnL2NlcnQvcmVwb3NpdG9yeS9jcHNfc3NsLnBkZjAIBgZngQwBAgIwRAYDVR0fBD0wOzA5oDegNYYzaHR0cDovL2NybC5pbmNvbW1vbi1yc2Eub3JnL0luQ29tbW9uUlNBU2VydmVyQ0EuY3JsMHUGCCsGAQUFBwEBBGkwZzA+BggrBgEFBQcwAoYyaHR0cDovL2NydC51c2VydHJ1c3QuY29tL0luQ29tbW9uUlNBU2VydmVyQ0FfMi5jcnQwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wHQYDVR0RBBYwFIIScHJvZC5ub3RpZnkudXcuZWR1MIIBfgYKKwYBBAHWeQIEAgSCAW4EggFqAWgAdgBGpVXrdfqRIDC1oolp9PN9ESxBdL79SbiFq/L8cP5tRwAAAXHmEwCJAAAEAwBHMEUCIASUNKIZlGflb1OWW4H6XRIKNDoS5giFOeJdJfsn/KVdAiEAiamkjSNEXwy9PMEHoq75k1ttRf8ct7CmG3+v9iR1FH8AdgDfpV6raIJPH2yt7rhfTj5a6s2iEqRqXo47EsAgRFwqcwAAAXHmEwCxAAAEAwBHMEUCIF/3aVFxeI/2Mkf9lyUJZ1FT1Glp3YYfn5OF0YyKYDxmAiEA5Ii90HscO77N/YaR7uH369dCKtzsYbIJiIsePwWbttAAdgBvU3asMfAxGdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAXHmEwCCAAAEAwBHMEUCIBBxEQuktXl08fg1VKGv3s3aFuf/ul9H0uDYwwfX5AT+AiEA8fxuo5wcUQpYSyTKbETAe2zfcvEgwfRxjyCZJ8oVslcwDQYJKoZIhvcNAQELBQADggEBAHh60jEKiZ/v0S9vUS+0oabOq7DNWhF4l164jY8s+hgcBxKiQVelIgvP3mK1uJyOxmzj8V1+Bu1b0OnCZbu1OfLp3ZPGnvr7luek0GjJfaKEGMLgQwr+7YAD4RB9c0ymWIE1ns+r2ELbC12lCeuW2oznSErOrwNPHEc713al2Gp8h11wAAvm8K8Ug0eOulwNBqV4FwHQ+gX5R35jOAasebB1jOs4RysVP6weoTvUkX/ZOGLitfxr2+SalbiKcIIfBA16WPaxXZyB9BV3f3Ctkl/7wOzRsmxt8S25+p0XO3evECCAau0ggmxwNE2aHv1TGbSUQ5nyADG5finDGy65YjY='
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='
  - name: ADMIN_GROUP
    value: 'u_acadev_notify-production-support'
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: notify.uw.edu-secrets
    secretKey: django-secret
  enrollmentQueueArn:
    name: SQS_ENROLLMENT_QUEUE_ARN
    secretName: notify.uw.edu-secrets
    secretKey: sqs-enrollment-queue-arn
  enrollmentKeyId:
    name: SQS_ENROLLMENT_KEY_ID
    secretName: notify.uw.edu-secrets
    secretKey: sqs-enrollment-key-id
  enrollmentKey:
    name: SQS_ENROLLMENT_KEY
    secretName: notify.uw.edu-secrets
    secretKey: sqs-enrollment-key
  googleAnalyticsKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: notify.uw.edu-secrets
    secretKey: google-analytics-key
  notificationAPIAuthToken:
    name: NWS_AUTH_SECRET
    secretName: notify.uw.edu-secrets
    secretKey: nws-auth-secret
