ingress:
  enabled: true
  tls:
    notify:
      secretName: test.notify.uw.edu-cert
      hosts:
        - test.notify.uw.edu
  hosts:
    notify:
      host: test.notify.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
externalService:
  enabled: true
  name: notify-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.34
  servicePort: 5432
database:
  engine: postgres
  name: notify-test
  hostname: notify-db-service
  secretName: test.notify.uw.edu-db
repo: notify
instance: test
image:
  repository: registry.hub.docker.com/acait/notify
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: true
  jobs:
    - name: unsubscribe-registered
      schedule: '55 15-23 * * 1-5'
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py registration_consumer)"]'
certs:
  mounted: true
  certPath: /certs/test.notify.uw.edu-uwca.cert
  keyPath: /certs/test.notify.uw.edu-uwca.key
  secretName: test.notify.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: test
  - name: GWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: SWS_ENV
    value: EVAL
  - name: NWS_ENV
    value: EVAL
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test.notify.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: test.notify.uw.edu
  - name: SAML_USER_ATTRIBUTE
    value: eppn
  - name: SP_CERT
    value: 'MIIG+DCCBeCgAwIBAgIQL2nzM/Ef3GrbOFeCYTxJMjANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjEfMB0GA1UEAxMWSW5Db21tb24gUlNBIFNlcnZlciBDQTAeFw0yMDAyMTIwMDAwMDBaFw0yMjAyMTEyMzU5NTlaMIGvMQswCQYDVQQGEwJVUzEOMAwGA1UEERMFOTgxOTUxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1NlYXR0bGUxGTAXBgNVBAkTEDQ1NDUgMTV0aCBBdmUgTkUxITAfBgNVBAoTGFVuaXZlcnNpdHkgb2YgV2FzaGluZ3RvbjEOMAwGA1UECxMFVVctSVQxGzAZBgNVBAMTEnRlc3Qubm90aWZ5LnV3LmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANOT8xTIWrDUjof42/CpM1/ivl+ifA3fT9J6H8Z7d4lW+ibw0gUlB2sYxARvr00LrrXMKJe8gpa/KK/pr94XyXKtE+BQxQlhS+KMDkhSKTfL3C4CJHb/7qRZ4ogprR3fvBXcN3/41MrvihlWfHc4raGO5KOAJeFc4rkKMil4IU5SbSEozfGK2Re27jR/E+2qo0wpWe1EnAaLYvdM0X7Nin4h8XQZanLLfd7EmImEakAGR5nEkpqsr1WA2/dZDqg+VuP6uGsBS/VraIVZZNNYjRcMCtvdm9z5Jt3In1Lsewa3hfnqE9zFzSBDsQZbYjthdJl5Ii8bR7FDdv52sNi2y7cCAwEAAaOCA0YwggNCMB8GA1UdIwQYMBaAFB4Fo3ePbJbiW4dLprSGrHEADOc4MB0GA1UdDgQWBBSmotJXwJkQaPTgo4HPnIzkfCWUkjAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwZwYDVR0gBGAwXjBSBgwrBgEEAa4jAQQDAQEwQjBABggrBgEFBQcCARY0aHR0cHM6Ly93d3cuaW5jb21tb24ub3JnL2NlcnQvcmVwb3NpdG9yeS9jcHNfc3NsLnBkZjAIBgZngQwBAgIwRAYDVR0fBD0wOzA5oDegNYYzaHR0cDovL2NybC5pbmNvbW1vbi1yc2Eub3JnL0luQ29tbW9uUlNBU2VydmVyQ0EuY3JsMHUGCCsGAQUFBwEBBGkwZzA+BggrBgEFBQcwAoYyaHR0cDovL2NydC51c2VydHJ1c3QuY29tL0luQ29tbW9uUlNBU2VydmVyQ0FfMi5jcnQwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wHQYDVR0RBBYwFIISdGVzdC5ub3RpZnkudXcuZWR1MIIBfAYKKwYBBAHWeQIEAgSCAWwEggFoAWYAdQBGpVXrdfqRIDC1oolp9PN9ESxBdL79SbiFq/L8cP5tRwAAAXA7OmxOAAAEAwBGMEQCIAwAEa3Y2ZYBSTfG+weVmPyH2bmcSdKHW4i439CdmGMKAiBVLDCAoUdPx7toazO0dWBFjIWEVMstI+qof2X73OVRWgB2AN+lXqtogk8fbK3uuF9OPlrqzaISpGpejjsSwCBEXCpzAAABcDs6bX4AAAQDAEcwRQIgWIbib/6PzBgFMQqFQF+KdeGk3ocogP8JmlaeiAViBM8CIQDBbWjsCi65k4nB2axMZpQb5Bmb9+h1nAFN7NSKCNP+IwB1AEHIyrHfIkZKEMahOglCh15OMYsbA+vrS8do8JBilgb2AAABcDs6bD0AAAQDAEYwRAIgT8mhGMm4PAxfuUkpb2hnqWL5zjfg7+m4cbQZ6bmrJB8CICx0QKb9+8PX41pVyAbFb9fMIZOput7xo62zNTBwyBXZMA0GCSqGSIb3DQEBCwUAA4IBAQBgsAiBTIi5+JJsN36qqvQlBsOnj2LlWgKhLGrD2CZCKSy/wlB+RAyD1yGnOL4Vj9ucacoadgAzw9qEW4JL3nvfu+0JJSQUAX8YAOPdPJ7F0vV3uc1POYtK7nDXEhIrF3oRsn3ejnEMcerHJChLb+toemahrKv+o7xu3v5H7PtbDlufdp6pBLS4zbxE4hCdLSJj2H0T0L8PlfdS7EdQWxAwj0MVcXOn4J2CJa40WWp5MyxsTnxSNq+N1InupkjKmHDCTWaeFL6RIuzB1W+gff59fuIM5D6gyhR8OMiM/eubFqUha+6t8qtmOiITmuSkZMkHpas5FdnXN7yVbqGpvuCi'
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='
  - name: ADMIN_GROUP
    value: 'u_acadev_notifydev-support'
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.notify.uw.edu-django-secret-key
    secretKey: django-secret
  enrollmentQueueArn:
    name: SQS_ENROLLMENT_QUEUE_ARN
    secretName: test.notify.uw.edu-sqs-enrollment
    secretKey: sqs-queue-arn
  enrollmentKeyId:
    name: SQS_ENROLLMENT_KEY_ID
    secretName: test.notify.uw.edu-sqs-enrollment
    secretKey: sqs-key-id
  enrollmentKey:
    name: SQS_ENROLLMENT_KEY
    secretName: test.notify.uw.edu-sqs-enrollment
    secretKey: sqs-key
  googleAnalyticsKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: test.notify.uw.edu-google-analytics-key
    secretKey: google-analytics-key
