ingress:
  enabled: true
  type: nginx
  tls:
    notify-test:
      secretName: notify-test.uw.edu
      hosts:
        - notify-test.uw.edu
  hosts:
    notify-test:
      host: notify-test.uw.edu
      paths:
        - '/'
    notify-test-aca-aws:
      host: notify-test.aca-aws.s.uw.edu
      paths:
        - '/'
database:
  engine: postgres
  name: notify
  hostname: notify-db-test-service
  secretName: notify-db-test
externalService:
  enabled: true
  name: notify-db-test-service
  type: ClusterIP
  serviceAddress: 172.18.2.3
  servicePort: 5432
repo: notify
instance: dev
replicaCount: 2
minReplicas: 2
maxReplicas: 6
targetAverageUtilization: 90
resources:
  limits:
    cpu: 600m
  requests:
    cpu: 200m
image:
  repository: registry.hub.docker.com/acait/notify
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: true
  jobs:
    - name: unsubscribe-registered
      schedule: '55 15-23 * * 1-5'
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py registration_consumer)"]'
certs:
  mounted: true
  certPath: /certs/notify-test.uw.edu-uwca.cert
  keyPath: /certs/notify-test.uw.edu-uwca.key
  secretName: notify-test-uwca-certs
environmentVariables:
  - name: ENV
    value: test
  - name: CERT_PATH
    value: /certs/notify-test.uw.edu-uwca.cert
  - name: KEY_PATH
    value: /certs/notify-test.uw.edu-uwca.key
  - name: GWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: SWS_ENV
    value: EVAL
  - name: NWS_ENV
    value: EVAL
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://notify-test.s.uw.edu/shibboleth
  - name: CLUSTER_CNAME
    value: notify-test.uw.edu
  - name: SAML_USER_ATTRIBUTE
    value: eppn
  - name: SP_CERT
    value: 'MIIG+DCCBeCgAwIBAgIQL2nzM/Ef3GrbOFeCYTxJMjANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjEfMB0GA1UEAxMWSW5Db21tb24gUlNBIFNlcnZlciBDQTAeFw0yMDAyMTIwMDAwMDBaFw0yMjAyMTEyMzU5NTlaMIGvMQswCQYDVQQGEwJVUzEOMAwGA1UEERMFOTgxOTUxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1NlYXR0bGUxGTAXBgNVBAkTEDQ1NDUgMTV0aCBBdmUgTkUxITAfBgNVBAoTGFVuaXZlcnNpdHkgb2YgV2FzaGluZ3RvbjEOMAwGA1UECxMFVVctSVQxGzAZBgNVBAMTEnRlc3Qubm90aWZ5LnV3LmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANOT8xTIWrDUjof42/CpM1/ivl+ifA3fT9J6H8Z7d4lW+ibw0gUlB2sYxARvr00LrrXMKJe8gpa/KK/pr94XyXKtE+BQxQlhS+KMDkhSKTfL3C4CJHb/7qRZ4ogprR3fvBXcN3/41MrvihlWfHc4raGO5KOAJeFc4rkKMil4IU5SbSEozfGK2Re27jR/E+2qo0wpWe1EnAaLYvdM0X7Nin4h8XQZanLLfd7EmImEakAGR5nEkpqsr1WA2/dZDqg+VuP6uGsBS/VraIVZZNNYjRcMCtvdm9z5Jt3In1Lsewa3hfnqE9zFzSBDsQZbYjthdJl5Ii8bR7FDdv52sNi2y7cCAwEAAaOCA0YwggNCMB8GA1UdIwQYMBaAFB4Fo3ePbJbiW4dLprSGrHEADOc4MB0GA1UdDgQWBBSmotJXwJkQaPTgo4HPnIzkfCWUkjAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwZwYDVR0gBGAwXjBSBgwrBgEEAa4jAQQDAQEwQjBABggrBgEFBQcCARY0aHR0cHM6Ly93d3cuaW5jb21tb24ub3JnL2NlcnQvcmVwb3NpdG9yeS9jcHNfc3NsLnBkZjAIBgZngQwBAgIwRAYDVR0fBD0wOzA5oDegNYYzaHR0cDovL2NybC5pbmNvbW1vbi1yc2Eub3JnL0luQ29tbW9uUlNBU2VydmVyQ0EuY3JsMHUGCCsGAQUFBwEBBGkwZzA+BggrBgEFBQcwAoYyaHR0cDovL2NydC51c2VydHJ1c3QuY29tL0luQ29tbW9uUlNBU2VydmVyQ0FfMi5jcnQwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wHQYDVR0RBBYwFIISdGVzdC5ub3RpZnkudXcuZWR1MIIBfAYKKwYBBAHWeQIEAgSCAWwEggFoAWYAdQBGpVXrdfqRIDC1oolp9PN9ESxBdL79SbiFq/L8cP5tRwAAAXA7OmxOAAAEAwBGMEQCIAwAEa3Y2ZYBSTfG+weVmPyH2bmcSdKHW4i439CdmGMKAiBVLDCAoUdPx7toazO0dWBFjIWEVMstI+qof2X73OVRWgB2AN+lXqtogk8fbK3uuF9OPlrqzaISpGpejjsSwCBEXCpzAAABcDs6bX4AAAQDAEcwRQIgWIbib/6PzBgFMQqFQF+KdeGk3ocogP8JmlaeiAViBM8CIQDBbWjsCi65k4nB2axMZpQb5Bmb9+h1nAFN7NSKCNP+IwB1AEHIyrHfIkZKEMahOglCh15OMYsbA+vrS8do8JBilgb2AAABcDs6bD0AAAQDAEYwRAIgT8mhGMm4PAxfuUkpb2hnqWL5zjfg7+m4cbQZ6bmrJB8CICx0QKb9+8PX41pVyAbFb9fMIZOput7xo62zNTBwyBXZMA0GCSqGSIb3DQEBCwUAA4IBAQBgsAiBTIi5+JJsN36qqvQlBsOnj2LlWgKhLGrD2CZCKSy/wlB+RAyD1yGnOL4Vj9ucacoadgAzw9qEW4JL3nvfu+0JJSQUAX8YAOPdPJ7F0vV3uc1POYtK7nDXEhIrF3oRsn3ejnEMcerHJChLb+toemahrKv+o7xu3v5H7PtbDlufdp6pBLS4zbxE4hCdLSJj2H0T0L8PlfdS7EdQWxAwj0MVcXOn4J2CJa40WWp5MyxsTnxSNq+N1InupkjKmHDCTWaeFL6RIuzB1W+gff59fuIM5D6gyhR8OMiM/eubFqUha+6t8qtmOiITmuSkZMkHpas5FdnXN7yVbqGpvuCi'
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='
  - name: ADMIN_GROUP
    value: 'u_acadev_notifydev-support'
  - name: GOOGLE_ANALYTICS_KEY
    value: ''
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: notify-test-django-secret
    secretKey: django-secret
  enrollmentQueueArn:
    name: ENROLLMENT_QUEUE_ARN
    secretName: notify-test-enrollment-queue-arn
    secretKey: enrollment-queue-arn
  enrollmentKeyId:
    name: ENROLLMENT_KEY_ID
    secretName: notify-test-enrollment-key-id
    secretKey: enrollment-key-id
  enrollmentKey:
    name: ENROLLMENT_KEY
    secretName: notify-test-enrollment-key
    secretKey: enrollment-key
