ingress:
  enabled: true
  tls:
    notify:
      secretName: test.notify.uw.edu-ingress-cert
      hosts:
        - test.notify.uw.edu
  hosts:
    notify:
      host: test.notify.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: notify-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.34
  servicePort: 5432
database:
  engine: postgres
  name: notify-test
  hostname: notify-db-service
  secretName: test.notify.uw.edu-sql-secrets
repo: notify
instance: test
image:
  repository: registry.hub.docker.com/acait/notify
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: false
  jobs:
    - name: unsubscribe-registered
      schedule: "55 15-23 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["registration_consumer"]
certs:
  mounted: true
  certPath: /certs/test.notify.uw.edu-uwca.cert
  keyPath: /certs/test.notify.uw.edu-uwca.key
  secretName: test.notify.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: test

  - name: KWS_ENV
    value: PROD

  - name: PWS_ENV
    value: PROD

  - name: SWS_ENV
    value: PROD

  - name: NWS_ENV
    value: EVAL

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test.notify.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: test.notify.uw.edu
  - name: SAML_USER_ATTRIBUTE
    value: eppn
    #  - name: SP_CERT
    #value: 'MIIG+DCCBeCgAwIBAgIQL2nzM/Ef3GrbOFeCYTxJMjANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjEfMB0GA1UEAxMWSW5Db21tb24gUlNBIFNlcnZlciBDQTAeFw0yMDAyMTIwMDAwMDBaFw0yMjAyMTEyMzU5NTlaMIGvMQswCQYDVQQGEwJVUzEOMAwGA1UEERMFOTgxOTUxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1NlYXR0bGUxGTAXBgNVBAkTEDQ1NDUgMTV0aCBBdmUgTkUxITAfBgNVBAoTGFVuaXZlcnNpdHkgb2YgV2FzaGluZ3RvbjEOMAwGA1UECxMFVVctSVQxGzAZBgNVBAMTEnRlc3Qubm90aWZ5LnV3LmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANOT8xTIWrDUjof42/CpM1/ivl+ifA3fT9J6H8Z7d4lW+ibw0gUlB2sYxARvr00LrrXMKJe8gpa/KK/pr94XyXKtE+BQxQlhS+KMDkhSKTfL3C4CJHb/7qRZ4ogprR3fvBXcN3/41MrvihlWfHc4raGO5KOAJeFc4rkKMil4IU5SbSEozfGK2Re27jR/E+2qo0wpWe1EnAaLYvdM0X7Nin4h8XQZanLLfd7EmImEakAGR5nEkpqsr1WA2/dZDqg+VuP6uGsBS/VraIVZZNNYjRcMCtvdm9z5Jt3In1Lsewa3hfnqE9zFzSBDsQZbYjthdJl5Ii8bR7FDdv52sNi2y7cCAwEAAaOCA0YwggNCMB8GA1UdIwQYMBaAFB4Fo3ePbJbiW4dLprSGrHEADOc4MB0GA1UdDgQWBBSmotJXwJkQaPTgo4HPnIzkfCWUkjAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwZwYDVR0gBGAwXjBSBgwrBgEEAa4jAQQDAQEwQjBABggrBgEFBQcCARY0aHR0cHM6Ly93d3cuaW5jb21tb24ub3JnL2NlcnQvcmVwb3NpdG9yeS9jcHNfc3NsLnBkZjAIBgZngQwBAgIwRAYDVR0fBD0wOzA5oDegNYYzaHR0cDovL2NybC5pbmNvbW1vbi1yc2Eub3JnL0luQ29tbW9uUlNBU2VydmVyQ0EuY3JsMHUGCCsGAQUFBwEBBGkwZzA+BggrBgEFBQcwAoYyaHR0cDovL2NydC51c2VydHJ1c3QuY29tL0luQ29tbW9uUlNBU2VydmVyQ0FfMi5jcnQwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wHQYDVR0RBBYwFIISdGVzdC5ub3RpZnkudXcuZWR1MIIBfAYKKwYBBAHWeQIEAgSCAWwEggFoAWYAdQBGpVXrdfqRIDC1oolp9PN9ESxBdL79SbiFq/L8cP5tRwAAAXA7OmxOAAAEAwBGMEQCIAwAEa3Y2ZYBSTfG+weVmPyH2bmcSdKHW4i439CdmGMKAiBVLDCAoUdPx7toazO0dWBFjIWEVMstI+qof2X73OVRWgB2AN+lXqtogk8fbK3uuF9OPlrqzaISpGpejjsSwCBEXCpzAAABcDs6bX4AAAQDAEcwRQIgWIbib/6PzBgFMQqFQF+KdeGk3ocogP8JmlaeiAViBM8CIQDBbWjsCi65k4nB2axMZpQb5Bmb9+h1nAFN7NSKCNP+IwB1AEHIyrHfIkZKEMahOglCh15OMYsbA+vrS8do8JBilgb2AAABcDs6bD0AAAQDAEYwRAIgT8mhGMm4PAxfuUkpb2hnqWL5zjfg7+m4cbQZ6bmrJB8CICx0QKb9+8PX41pVyAbFb9fMIZOput7xo62zNTBwyBXZMA0GCSqGSIb3DQEBCwUAA4IBAQBgsAiBTIi5+JJsN36qqvQlBsOnj2LlWgKhLGrD2CZCKSy/wlB+RAyD1yGnOL4Vj9ucacoadgAzw9qEW4JL3nvfu+0JJSQUAX8YAOPdPJ7F0vV3uc1POYtK7nDXEhIrF3oRsn3ejnEMcerHJChLb+toemahrKv+o7xu3v5H7PtbDlufdp6pBLS4zbxE4hCdLSJj2H0T0L8PlfdS7EdQWxAwj0MVcXOn4J2CJa40WWp5MyxsTnxSNq+N1InupkjKmHDCTWaeFL6RIuzB1W+gff59fuIM5D6gyhR8OMiM/eubFqUha+6t8qtmOiITmuSkZMkHpas5FdnXN7yVbqGpvuCi'
  - name: ADMIN_GROUP
    value: 'u_acadev_notifydev-support'

externalSecrets:
  enabled: true
  secrets:
    - name: test.notify.uw.edu-secrets
      externalKey: axdd/kv/data/notify/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: sqs-enrollment-queue-arn
          property: sqs-enrollment-queue-arn
        - name: sqs-enrollment-key-id
          property: sqs-enrollment-key-id
        - name: sqs-enrollment-key
          property: sqs-enrollment-key
        - name: google-analytics-key
          property: google-analytics-key
        - name: nws-auth-secret
          property: nws-auth-secret
        - name: email-sender-address
          property: email-sender-address
        - name: support-email-address
          property: support-email-address
    - name: test.notify.uw.edu-sql-secrets
      externalKey: axdd/kv/data/notify/test/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test.notify.uw.edu-uwca-certs
      externalKey: axdd/kv/data/notify/test/uwca-certs
      data:
        - name: test.notify.uw.edu-uwca.cert
          property: test.notify.uw.edu-uwca.cert
        - name: test.notify.uw.edu-uwca.key
          property: test.notify.uw.edu-uwca.key
    - name: test.notify.uw.edu-ic-certs
      externalKey: axdd/kv/data/notify/test/ic-certs
      data:
        - name: test.notify.uw.edu-ic.cert
          property: test.notify.uw.edu-ic.cert
    - name: test.notify.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.notify.uw.edu-secrets
    secretKey: django-secret
  enrollmentQueueArn:
    name: SQS_ENROLLMENT_QUEUE_ARN
    secretName: test.notify.uw.edu-secrets
    secretKey: sqs-enrollment-queue-arn
  enrollmentKeyId:
    name: SQS_ENROLLMENT_KEY_ID
    secretName: test.notify.uw.edu-secrets
    secretKey: sqs-enrollment-key-id
  enrollmentKey:
    name: SQS_ENROLLMENT_KEY
    secretName: test.notify.uw.edu-secrets
    secretKey: sqs-enrollment-key
  googleAnalyticsKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: test.notify.uw.edu-secrets
    secretKey: google-analytics-key
  notificationAPIAuthToken:
    name: NWS_AUTH_SECRET
    secretName: test.notify.uw.edu-secrets
    secretKey: nws-auth-secret
  emailSenderAddress:
    name: EMAIL_SENDER_ADDRESS
    secretName: test.notify.uw.edu-secrets
    secretKey: email-sender-address
  supportEmailAddress:
    name: SUPPORT_EMAIL_ADDRESS
    secretName: test.notify.uw.edu-secrets
    secretKey: support-email-address
  samlSPCert:
    name: SP_CERT
    secretName: test.notify.uw.edu-ic-certs
    secretKey: test.notify.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test.notify.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
