ingress:
  enabled: true
  tls:
    notify:
      secretName: test.notify.uw.edu-ingress-cert
      hosts:
        - test.notify.uw.edu
  hosts:
    notify:
      host: test.notify.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
    nginx.ingress.kubernetes.io/limit-rpm: "40"
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: notify-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.34
  servicePort: 5432
database:
  engine: postgres
  name: notify-test
  hostname: notify-db-service
  secretName: test.notify.uw.edu-sql-secrets
repo: notify
instance: test
image:
  repository: registry.hub.docker.com/acait/notify
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
cronjob:
  enabled: false
  jobs:
    - name: unsubscribe-registered
      schedule: "*/30 15-23 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["registration_consumer"]
certs:
  mounted: true
  certPath: /certs/test.notify.uw.edu-uwca.cert
  keyPath: /certs/test.notify.uw.edu-uwca.key
  secretName: test.notify.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: test

  - name: KWS_ENV
    value: PROD

  - name: PWS_ENV
    value: PROD

  - name: SWS_ENV
    value: EVAL

  - name: NWS_ENV
    value: EVAL
  - name: NWS_TIMEOUT
    value: "10"

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test.notify.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: test.notify.uw.edu
  - name: SAML_USER_ATTRIBUTE
    value: eppn
  - name: ADMIN_GROUP
    value: 'u_acadev_notifydev-support'

externalSecrets:
  enabled: true
  secrets:
    - name: test.notify.uw.edu-secrets
      externalKey: axdd/kv/data/notify/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: sqs-enrollment-queue-arn
          property: sqs-enrollment-queue-arn
        - name: sqs-enrollment-key-id
          property: sqs-enrollment-key-id
        - name: sqs-enrollment-key
          property: sqs-enrollment-key
        - name: google-analytics-key
          property: google-analytics-key
        - name: nws-auth-secret
          property: nws-auth-secret
        - name: email-sender-address
          property: email-sender-address
        - name: support-email-address
          property: support-email-address
    - name: test.notify.uw.edu-sql-secrets
      externalKey: axdd/kv/data/notify/test/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test.notify.uw.edu-uwca-certs
      externalKey: axdd/kv/data/notify/test/uwca-certs
      data:
        - name: test.notify.uw.edu-uwca.cert
          property: test.notify.uw.edu-uwca.cert
        - name: test.notify.uw.edu-uwca.key
          property: test.notify.uw.edu-uwca.key
    - name: test.notify.uw.edu-ic-certs
      externalKey: axdd/kv/data/notify/test/ic-certs
      data:
        - name: test.notify.uw.edu-ic.cert
          property: test.notify.uw.edu-ic.cert
    - name: test.notify.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.notify.uw.edu-secrets
    secretKey: django-secret
  enrollmentQueueArn:
    name: SQS_ENROLLMENT_QUEUE_ARN
    secretName: test.notify.uw.edu-secrets
    secretKey: sqs-enrollment-queue-arn
  enrollmentKeyId:
    name: SQS_ENROLLMENT_KEY_ID
    secretName: test.notify.uw.edu-secrets
    secretKey: sqs-enrollment-key-id
  enrollmentKey:
    name: SQS_ENROLLMENT_KEY
    secretName: test.notify.uw.edu-secrets
    secretKey: sqs-enrollment-key
  googleAnalyticsKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: test.notify.uw.edu-secrets
    secretKey: google-analytics-key
  notificationAPIAuthToken:
    name: NWS_AUTH_SECRET
    secretName: test.notify.uw.edu-secrets
    secretKey: nws-auth-secret
  emailSenderAddress:
    name: EMAIL_SENDER_ADDRESS
    secretName: test.notify.uw.edu-secrets
    secretKey: email-sender-address
  supportEmailAddress:
    name: SUPPORT_EMAIL_ADDRESS
    secretName: test.notify.uw.edu-secrets
    secretKey: support-email-address
  samlSPCert:
    name: SP_CERT
    secretName: test.notify.uw.edu-ic-certs
    secretKey: test.notify.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test.notify.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
